-- DropForeignKey
ALTER TABLE "Vehicle" DROP CONSTRAINT "Vehicle_TaxId_fkey";

-- AlterTable
ALTER TABLE "Vehicle" ALTER COLUMN "LineNotifyToken" DROP NOT NULL,
ALTER COLUMN "Note" DROP NOT NULL,
ALTER COLUMN "Img" DROP NOT NULL,
ALTER COLUMN "TaxId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Vehicle" ADD CONSTRAINT "Vehicle_TaxId_fkey" FOREIGN KEY ("TaxId") REFERENCES "Tax"("TaxId") ON DELETE SET NULL ON UPDATE CASCADE;
